services:
  actilde:
    image: nginx:stable-alpine-slim
    container_name: actilde
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    restart: unless-stopped
    ports:
      - 8080:80
#     networks:
#       - traefik-network
#     labels:
#       - "traefik.enable=true"
#       - "traefik.http.routers.actilde.entrypoints=https"
#       - "traefik.http.routers.actilde.rule=Host(`actilde.example.tld`)"
#       - "traefik.http.routers.actilde.tls.certresolver=cloudflare"

# networks:
#   traefik-network:
#     external: true
